[package]
name = "rankfast-web"
version.workspace = true
edition.workspace = true

[dependencies]
leptos = { workspace = true }
rankfast = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }

[lints]
workspace = true
